name: hevy_smolov_jr
description: Smolov Jr Calculator for Hevy
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_rearch: ^1.7.2
  freezed_annotation: ^3.1.0
  fuzzywuzzy: ^1.2.0
  http: ^1.2.2
  json_annotation: ^4.10.0
  rearch: ^1.16.1
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^3.2.5
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
